# Generated by Django 2.0 on 2020-01-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='systemParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameterName', models.CharField(max_length=255, verbose_name='参数别名')),
                ('parameterKey', models.CharField(max_length=255, verbose_name='参数名')),
                ('parameterValue', models.CharField(max_length=255, verbose_name='参数值')),
            ],
        ),
    ]
